- name: Deploy to EC2
  run: |
    scp -o StrictHostKeyChecking=no -i key.pem index.html ubuntu@${{ secrets.EC2_HOST }}:/tmp/

    ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
      sudo mv /tmp/index.html /var/www/html/index.html
      sudo systemctl restart nginx
    EOF
